const data = [
    {
        id: "1",
        titulo: "Biblia (RVR1960) Letra grande",
        descripcion: "La Biblia de estudio de la Reforma es un trabajo en conjunto con grandes estudiosos de la Biblia reconocidos a nivel internacional.",
        precio: "3000",
        stock: "4",
        categoria: "biblias",
        imagen: "https://i.ibb.co/RcxNS1q/biblia4.png",
    },
    {
        id: "2",
        titulo: 'Biblia (LBLA) Letra grande',
        descripcion: "La Biblia de estudio MacArthur es una obra del reconocido pastor John MacArthur, en la que realizó un profundo análisis de cada versículo y un minucioso estudio de cada pasaje difícil.",
        precio: "3000",
        stock: "5",
        categoria: 'biblias',
        imagen: "https://i.ibb.co/mhQSR1f/biblia5.png",
    },
    {
        id: "3",
        titulo: "Biblia (NVI) Letra grande",
        descripcion: "La Biblia de Estudio de Apologética contribuye a que el cristiano de hoy día pueda comprender mejor, defender y proclamar sus creencias en este tiempo de creciente relativismo moral y espiritual.",
        precio: "3000",
        stock: "6",
        categoria: "biblias",
        imagen: "https://i.ibb.co/Mp1tT1x/biblia6.png",
    },
    {
        id: "4",
        titulo: "Biblia de estudio de la Reforma",
        descripcion: "La Biblia de estudio de la Reforma es un trabajo en conjunto con grandes estudiosos de la Biblia reconocidos a nivel internacional.",
        precio: "15000",
        stock: "7",
        categoria: "bibliasdeestudio",
        imagen: "https://i.ibb.co/wK2bBb8/biblia1.png",
    },
    {
        id: "5",
        titulo: "Biblia de estudio MacArthur",
        descripcion: "La Biblia de estudio MacArthur es una obra del reconocido pastor John MacArthur, en la que realizó un profundo análisis de cada versículo y un minucioso estudio de cada pasaje difícil.",
        precio: "10000",
        stock: "8",
        categoria: "bibliasdeestudio",
        imagen: "https://i.ibb.co/N6GD2Md/biblia2.png",
    },
    {
        id: "6",
        titulo: "Biblia de estudio de Apologética",
        descripcion: "La Biblia de Estudio de Apologética contribuye a que el cristiano de hoy día pueda comprender mejor, defender y proclamar sus creencias en este tiempo de creciente relativismo moral y espiritual.",
        precio: "10000",
        stock: "9",
        categoria: "bibliasdeestudio",
        imagen: "https://i.ibb.co/RH4ndJy/biblia3.png",
    },
    {
        id: "7",
        titulo: "Institución de la religión cristiana",
        descripcion: "De gran importancia para la Reforma Protestante, la institución ha seguido siendo importante para la teología protestante durante casi cinco siglos.",
        precio: "20000",
        stock: "10",
        categoria: "libros",
        imagen: "https://i.ibb.co/wNBsCLj/libro1.png",
    },
    {
        id: "8",
        titulo: "El progreso del peregrino",
        descripcion: "El progreso del peregrino es una novela alegórica sobre la fe cristiana que relata el viaje de Cristiano a la Ciudad Celestial, buscando la salvación.",
        precio: "7000",
        stock: "11",
        categoria: "libros",
        imagen: "https://i.ibb.co/Jk6WdD9/libro2.png",
    },
    {
        id: "9",
        titulo: "El pecado remanente",
        descripcion: "Este libro es un manual de campo para la guerra que los soldados de Cristo deben librar durante toda su vida contra el pecado que permanece en ellos después de la conversión.",
        precio: "6000",
        stock: "12",
        categoria: "libros",
        imagen: "https://i.ibb.co/zVsmydV/libro3.png",
    },
]

export default data